/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vinho;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author AlunoCaxiasTemporári
 */
public class VinhoInterface extends javax.swing.JFrame {

    String carvalhoFrances = "não";
    String carvalhoAmericano = "não";
    String inox = "não";
    String emGarrafa = "não";
    ArrayList<Vinho> vinhosCadastrados = new ArrayList<Vinho>();

    String generoVitis;
    
    int contador = 1;
    
    ConsultaInterface consulta = new ConsultaInterface();

    public VinhoInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vitisGroup = new javax.swing.ButtonGroup();
        rbVinifera = new javax.swing.JRadioButton();
        rbLaBrusca = new javax.swing.JRadioButton();
        cbbTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lbCod = new javax.swing.JLabel();
        lbNomeRotulo = new javax.swing.JLabel();
        txtNomeRotulo = new javax.swing.JTextField();
        lbSafra = new javax.swing.JLabel();
        spinSafra = new javax.swing.JSpinner();
        lbTipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtProdutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbbCor = new javax.swing.JComboBox<>();
        lbClassificacao = new javax.swing.JLabel();
        cbbClassificacao = new javax.swing.JComboBox<>();
        lbDoc = new javax.swing.JLabel();
        txtDoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbUvaPredominante = new javax.swing.JLabel();
        txtUvaPredominante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spinPotencial = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cheCarvalhoFrances = new javax.swing.JCheckBox();
        lbEnvelhecimento = new javax.swing.JLabel();
        lbTempoMeses = new javax.swing.JLabel();
        spinTempoMeses = new javax.swing.JSpinner();
        cheCarvalhoAmericano = new javax.swing.JCheckBox();
        cheInox = new javax.swing.JCheckBox();
        cheEmGarrafa = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vitisGroup.add(rbVinifera);
        rbVinifera.setSelected(true);
        rbVinifera.setText("Vinífera");

        vitisGroup.add(rbLaBrusca);
        rbLaBrusca.setText("Labrusca");
        rbLaBrusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLaBruscaActionPerformed(evt);
            }
        });

        cbbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espumante", "Frizante", "Licoroso", "Vinho de Mesa", " " }));
        cbbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTipoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\AlunoCaxiasTemporári\\Desktop\\ProjetoVinho\\src\\main\\java\\icon\\background.png")); // NOI18N

        lbCod.setText("Cod    xxx");

        lbNomeRotulo.setText("Nome (rótulo)");

        lbSafra.setText("Safra");

        lbTipo.setText("Tipo");

        jLabel1.setText("Produtor");

        jLabel3.setText("Cor");

        cbbCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branco", "Tinto", "Rose" }));
        cbbCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbCorActionPerformed(evt);
            }
        });

        lbClassificacao.setText("Classificação");

        cbbClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suave", "Seco", "Demi-Sec" }));

        lbDoc.setText("D.O.C");

        jLabel4.setText("Gênero");

        lbUvaPredominante.setText("Uva Predominante");

        txtUvaPredominante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUvaPredominanteActionPerformed(evt);
            }
        });

        jLabel5.setText("Potencial de Guarda");

        jLabel6.setText("anos");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        cheCarvalhoFrances.setText("Carvalho Francês");
        cheCarvalhoFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheCarvalhoFrancesActionPerformed(evt);
            }
        });

        lbEnvelhecimento.setText("Envelhecimento");

        lbTempoMeses.setText("Tempo em Meses");

        cheCarvalhoAmericano.setText("Carvalho Americano");
        cheCarvalhoAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheCarvalhoAmericanoActionPerformed(evt);
            }
        });

        cheInox.setText("Inox");

        cheEmGarrafa.setText("Em Garrafa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEnvelhecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lbTempoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(spinTempoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cheCarvalhoFrances, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cheCarvalhoAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cheInox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cheEmGarrafa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEnvelhecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTempoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinTempoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cheCarvalhoFrances)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cheCarvalhoAmericano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cheInox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cheEmGarrafa)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        menuMenu.setText("Menu");

        jMenuItem1.setText("Consultar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuMenu.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        menuMenu.add(jMenuItem2);

        jMenuBar1.add(menuMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbCor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinSafra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbCod, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(cbbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbLaBrusca)
                            .addComponent(rbVinifera)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(lbUvaPredominante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinPotencial, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUvaPredominante, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomeRotulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinSafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbVinifera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbLaBrusca)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUvaPredominante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUvaPredominante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinPotencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelar))
                .addGap(19, 19, 19))
        );

        lbCod.getAccessibleContext().setAccessibleName("Cod");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        consulta.setVisible(true);
        
        for(Vinho vinho : vinhosCadastrados)
        {
            consulta.txtAreaConsulta.append((vinho.ImprimirDados(contador) + "\n\n"));
            contador++;
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    // TODO add your handling code here:
    private void cheCarvalhoFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheCarvalhoFrancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheCarvalhoFrancesActionPerformed
    // TODO add your handling code here:
    private void cbbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTipoActionPerformed
    // TODO add your handling code here:
    private void rbLaBruscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLaBruscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLaBruscaActionPerformed
    // TODO add your handling code here:
    private void txtUvaPredominanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUvaPredominanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUvaPredominanteActionPerformed
    // TODO add your handling code here:
    private void cheCarvalhoAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheCarvalhoAmericanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheCarvalhoAmericanoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        try
        {
        String nomeRotulo = txtNomeRotulo.getText();
        String produtor = txtProdutor.getText();
        String doc = txtDoc.getText();
        String classificacao = cbbClassificacao.getSelectedItem().toString();
        String cor = cbbCor.getSelectedItem().toString();
        int safra = (int) spinSafra.getValue();
        String tipo = cbbTipo.getSelectedItem().toString();
        int tempoEnvelhecimento = (int) spinTempoMeses.getValue();

        if (cheCarvalhoFrances.isSelected()) {
            carvalhoFrances = "sim";
        }

        if (cheCarvalhoAmericano.isSelected()) {
            carvalhoAmericano = "sim";
        }

        if (cheInox.isSelected()) {
            inox = "sim";
        }

        if (cheEmGarrafa.isSelected()) {
            emGarrafa = "sim";
        }

        if (rbVinifera.isSelected()) {
            generoVitis = "Vinifera";
        } else if (rbLaBrusca.isSelected()) {
            generoVitis = "Labrusca";
        }
        int potencialGuarda = (int) spinPotencial.getValue();
        String uvaPredominante = txtUvaPredominante.getText();

        Vinho vinho = new Vinho(
                nomeRotulo,
                produtor,
                doc,
                classificacao,
                cor,
                safra,
                tipo,
                tempoEnvelhecimento,
                carvalhoFrances,
                carvalhoAmericano,
                inox,
                emGarrafa,
                generoVitis,
                potencialGuarda,
                uvaPredominante
        );

        vinhosCadastrados.add(vinho);

        JOptionPane.showMessageDialog(this, "Vinho cadastrado com sucesso.");
        limpar();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Não foi possível cadastrar. " + e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cbbCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbCorActionPerformed
    public void limpar() {

        txtNomeRotulo.setText("");
        txtProdutor.setText("");
        txtDoc.setText("");
        txtUvaPredominante.setText("");

        cbbCor.setSelectedIndex(0);
        spinSafra.setValue(0);
        spinTempoMeses.setValue(0);
        spinPotencial.setValue(0);

        cbbTipo.setSelectedIndex(0);
        cbbCor.setSelectedIndex(0);
        cbbClassificacao.setSelectedIndex(0);

        cheCarvalhoFrances.setSelected(false);
        cheCarvalhoAmericano.setSelected(false);
        cheInox.setSelected(false);
        cheEmGarrafa.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VinhoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VinhoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VinhoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VinhoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VinhoInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbbClassificacao;
    private javax.swing.JComboBox<String> cbbCor;
    private javax.swing.JComboBox<String> cbbTipo;
    private javax.swing.JCheckBox cheCarvalhoAmericano;
    private javax.swing.JCheckBox cheCarvalhoFrances;
    private javax.swing.JCheckBox cheEmGarrafa;
    private javax.swing.JCheckBox cheInox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbClassificacao;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbDoc;
    private javax.swing.JLabel lbEnvelhecimento;
    private javax.swing.JLabel lbNomeRotulo;
    private javax.swing.JLabel lbSafra;
    private javax.swing.JLabel lbTempoMeses;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbUvaPredominante;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JRadioButton rbLaBrusca;
    private javax.swing.JRadioButton rbVinifera;
    private javax.swing.JSpinner spinPotencial;
    private javax.swing.JSpinner spinSafra;
    private javax.swing.JSpinner spinTempoMeses;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtNomeRotulo;
    private javax.swing.JTextField txtProdutor;
    private javax.swing.JTextField txtUvaPredominante;
    private javax.swing.ButtonGroup vitisGroup;
    // End of variables declaration//GEN-END:variables
}
